[package]
name = "_templates_"
version = "0.1.0"
edition = "2021"
default-run = "_templates_"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
